import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { GetStaticProps } from 'next'
import { HomeData, SharedPageProps } from '@/types'
import { fetchSiteSettings } from '../lib/fetchSiteSettings'
import { client } from '@/lib/client'

interface HomeProps extends SharedPageProps {
  homeData: HomeData
}

const Home: React.FC<HomeProps> = ({ homeData }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{homeData.body}</main>
    </>
  )
}

/**
 * Initial Props
 */

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const [homeData, siteSettings] = await Promise.all([
    client.getHomepage(),
    fetchSiteSettings(),
  ])
  return { props: { homeData, siteSettings }, revalidate: 10 }
}

export default Home
