import { PostData } from './types'

export const posts: Record<string, PostData> = {
  'post-1': { title: 'Post #1', body: 'lorem ipsum' },
  'post-2': { title: 'Post #2', body: 'lorem ipsum' },
  'post-3': { title: 'Post #3', body: 'lorem ipsum' },
  // 👇 Not generated by getStaticPaths 👇
  'post-4': { title: 'Post #3', body: 'lorem ipsum' },
  'post-5': { title: 'Post #3', body: 'lorem ipsum' },
}
